// Automatically generated by generate-projects-data.mjs. Do not edit manually.

export interface Project {
  id: number;
  title: string;
  subtitle: string;
  category: "Editing" | "Marketing" | "Motion";
  description: string;
  video: string;
  poster: string;
  tags: string[];
}

export const projects: Project[] = [
  {
    "id": 1,
    "title": "Midnight Motion",
    "subtitle": "A Study in Movement",
    "category": "Editing",
    "description": "Cinematic exploration of movement and shadow — crafted through meticulous editorial pacing and dramatic color grading.",
    "video": "/video/opt_IMG_0019.mp4",
    "poster": "/video/thumb_opt_IMG_0019.jpg",
    "tags": [
      "Premiere Pro",
      "Color Grading",
      "Cinematic"
    ]
  },
  {
    "id": 2,
    "title": "Frame Theory",
    "subtitle": "Visual Storytelling",
    "category": "Motion",
    "description": "Dynamic motion graphics sequence blending typography, form, and rhythm into a compelling visual narrative.",
    "video": "/video/opt_IMG_0772.mp4",
    "poster": "/video/thumb_opt_IMG_0772.jpg",
    "tags": [
      "After Effects",
      "Motion Design",
      "Typography"
    ]
  },
  {
    "id": 3,
    "title": "Visual Pulse",
    "subtitle": "Commercial Campaign",
    "category": "Marketing",
    "description": "High-energy commercial piece engineered for maximum engagement — driving brand awareness through visual impact.",
    "video": "/video/opt_IMG_2652.mp4",
    "poster": "/video/thumb_opt_IMG_2652.jpg",
    "tags": [
      "Paid Social",
      "Brand Strategy",
      "Conversion"
    ]
  },
  {
    "id": 4,
    "title": "Motion Narrative",
    "subtitle": "Editorial Short",
    "category": "Editing",
    "description": "Intimate editorial short capturing raw emotion through deliberate pacing and atmospheric sound design.",
    "video": "/video/opt_IMG_3024.mp4",
    "poster": "/video/thumb_opt_IMG_3024.jpg",
    "tags": [
      "Documentary",
      "Sound Design",
      "Storytelling"
    ]
  },
  {
    "id": 5,
    "title": "Cinematic Flow",
    "subtitle": "Brand Film",
    "category": "Motion",
    "description": "Fluid brand film merging sleek transitions with bold compositions — a visual identity brought to life.",
    "video": "/video/opt_IMG_3507.mp4",
    "poster": "/video/thumb_opt_IMG_3507.jpg",
    "tags": [
      "Direction",
      "3D Animation",
      "Branding"
    ]
  },
  {
    "id": 6,
    "title": "Golden Hour",
    "subtitle": "Performance Ad",
    "category": "Marketing",
    "description": "Performance-driven ad campaign bathed in warm tones, optimized for scroll-stopping impact across platforms.",
    "video": "/video/opt_IMG_3956.mp4",
    "poster": "/video/thumb_opt_IMG_3956.jpg",
    "tags": [
      "Ad Creative",
      "A/B Testing",
      "ROI Driven"
    ]
  },
  {
    "id": 7,
    "title": "Silent Frames",
    "subtitle": "Art Direction",
    "category": "Editing",
    "description": "Contemplative art piece exploring stillness within motion — every frame composed with editorial precision.",
    "video": "/video/opt_IMG_3966.mp4",
    "poster": "/video/thumb_opt_IMG_3966.jpg",
    "tags": [
      "Art Direction",
      "Post-Production",
      "Grading"
    ]
  }
];
